[tool.poetry]
name = "cypher"
version = "0.1.0"
description = ""
authors = ["Harry Hsu <stmharry@hashgreen.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
clvm-tools = "^0.4.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
